feat: Modify entity contents
SWIDX/Eats-Mate-Backend pull request #21
Opened 2022-08-06 07:19 UTC by xeangit

글 순서 idx -> id로 수정,
@column category, rate 추가 후 entity 사용 범위 전체 수정

2022-08-06 11:06 UTC, Queue-ri requested changes
7763bdb 커밋 메시지를
feat: Modify **review** entity contents 로 수정 부탁드립니다.
무슨 엔티티인지 CLI 히스토리 로그 상에서는 구분이 잘 안되어서요.

---
Relates to #12.

2022-08-07 07:02 UTC, Queue-ri approved these changes

2022-08-10 04:14 UTC, yyoonnooyy approved these changes

2022-08-10 04:14 UTC, yyoonnooyy approved these changes

2022-08-10 07:49 UTC, tlsdhsdb approved these changes

2022-08-10 07:55 UTC, merged